import { Scenario } from './types';

export const supplyChainScenario: Scenario = {
  id: 'supplychain',
  industry: 'Supply Chain',
  approvalRole: 'Chief Operations Officer',
  humanTeamLabel: 'Operations Team',
  clock: {
    p0: '08:14',
    p1: '04:02',
    p2: '04:06',
    p3: '04:09',
    p4: '04:09',
    p5: '04:11',
  },
  countdown: null,
  money: {
    atRiskLabel: '$47M revenue exposed',
    atRiskValue: 47,
    recoveredLabel: '$44M protected · 2-day delay avoided',
    recoveredValue: 44,
    currency: 'USD',
  },
  nodes: [
    {
      id: 'node-hq-bangkok',
      name: 'Cymbal HQ — Bangkok',
      role: 'hq',
      coords: [100.5018, 13.7563],
      label: 'Bangkok HQ',
    },
    {
      id: 'node-disrupted-alpha',
      name: 'Meridian Port Hub — Node Alpha',
      role: 'disrupted',
      coords: [103.8198, 1.3521], // SE Asia Straits
      label: 'Meridian Port Hub (Offline)',
    },
    {
      id: 'node-reroute-alpha',
      name: 'North Bay Gateway — Node Beta',
      role: 'hub',
      coords: [121.4737, 31.2304], // East Asia hub
      label: 'North Bay Hub',
    },
    {
      id: 'node-reroute-beta',
      name: 'Oceanic Transit Hub — Node Gamma',
      role: 'hub',
      coords: [114.1694, 22.3193], // Southern coastal hub
      label: 'Oceanic Transit Hub',
    },
    {
      id: 'node-destination-apex',
      name: 'Global Logistics Center Apex',
      role: 'destination',
      coords: [139.6917, 35.6895], // Tokyo/Northeast Asia DC
      label: 'Destination DC Apex',
    },
  ],
  disruptedNodeId: 'node-disrupted-alpha',
  rerouteNodeIds: ['node-reroute-alpha', 'node-reroute-beta'],
  dialogue: {
    p0: "It's 8:14 AM on a Tuesday at Cymbal Logistics HQ in Bangkok. Global revenue is climbing and fulfillment health sits at a nominal 98.7% OTIF.",
    p1: 'Flash back to 4:02 AM while the operations team slept. Early environmental telemetry detects an OTIF tremor on primary SE Asia shipping routes.',
    p2: 'At 4:06 AM, Meridian Port Hub goes dark under extreme typhoon weather. 1,284 shipments and $47M in revenue are immediately exposed.',
    p3: 'At 4:09 AM, the autonomous agent swarm activates: Sentinel flags outage, Sourcing inspects alternate capacity, Logistics simulates dual-hub rerouting, and Finance bounds P&L impact.',
    p4: 'At 4:09 AM, the multi-agent swarm converges on an optimized mitigation plan. System enters hold awaiting COO authorization to commit reroute.',
    p5: 'At 4:11 AM, authorization is executed. Network reroutes instantly via North Bay & Oceanic Transit hubs: $44M revenue protected, 188 customer promises kept, OTIF restored.',
  },
  timing: {
    typeSpeedMs: 22,
    lineDelayMs: 500,
    staggerMs: 220,
  },
  agents: [
    {
      id: 'agent-sentinel',
      name: 'Sentinel Agent',
      role: '24/7 Threat & Anomaly Detection',
      accentColor: '#00BCD4', // Cyan
      script: [
        'Telemetry stream active — polling regional signal density...',
        'ALERT: Primary gateway Meridian Port Hub (Node Alpha) ping lost at 04:02 ICT.',
        'Supercell typhoon landfall verified — severe power & link failure.',
        'Marking Node Alpha as CRITICAL / OFFLINE. Triggering multi-agent swarm mobilization.',
      ],
    },
    {
      id: 'agent-sourcing',
      name: 'Sourcing Agent',
      role: 'Supplier & Capacity Intelligence',
      accentColor: '#00FF80', // Green
      script: [
        'Inspecting secondary port manifests and berth throughput...',
        'Querying inventory allocations across East & South Asia nodes...',
        'North Bay Gateway & Oceanic Transit confirmed 94% berth availability.',
        'Contractual SLAs validated — slot reservation ready.',
      ],
      dataResult: '3 viable suppliers found · lead-time +1 day',
    },
    {
      id: 'agent-logistics',
      name: 'Logistics Agent',
      role: 'Network & Transit Optimization',
      accentColor: '#FF9500', // Amber
      script: [
        'Modeling 1,284 affected cargo containers from Meridian Hub...',
        'Simulating split-freight routing via North Bay and Oceanic hubs...',
        'Route matrix computed: dual-hub split preserves delivery window.',
        'Vessel velocity bumped +2.5 knots to cover schedule variance.',
      ],
      dataResult: 'Optimal reroute via 2 hubs · +6% cost',
    },
    {
      id: 'agent-finance',
      name: 'Finance Agent',
      role: 'P&L & Exposure Quantification',
      accentColor: '#E91E63', // Rose/Red
      script: [
        'Ingesting bill-of-lading valuations for active affected manifests...',
        'Total raw revenue exposure evaluated: $47,000,000 USD.',
        'Reroute expense delta: +$280,000 operational surcharge.',
        'Net risk mitigation calculated: $44M revenue fully protected.',
      ],
      dataResult: 'Revenue exposure $47M · protect 44M',
    },
    {
      id: 'agent-comms',
      name: 'Comms Agent',
      role: 'Customer & Operations Dispatch',
      accentColor: '#9C27B0', // Purple
      script: [
        'Matching 188 high-priority enterprise accounts with at-risk orders...',
        'Drafting proactive delay notification dispatches with updated ETA...',
        'Staging executive briefing package for COO sign-off...',
        'Automated dispatch queue prepared.',
      ],
      dataResult: '84 accounts notified · brief ready',
    },
  ],
  resolutionBadges: ['Within SLA', 'Customer-notified', 'Audited'],
  outro: {
    title: '08:00 ICT — Operations Team Online',
    body: 'Reroute executed overnight via 2 alternate hubs. $44M revenue protected, 188 accounts safeguarded, OTIF restored to 97.2%.',
    footer: 'No action required.',
  },
  metrics: {
    hqLabel: 'Bangkok HQ',
    hqTimezone: 'ICT',
    companyName: 'Cymbal Logistics',
    phases: {
      p0: {
        revenueTotal: 8.42,
        revenueDeltaPct: 3.2,
        revenueTrend: 'up',
        revenueByRegion: [
          { id: 'sea', label: 'SE Asia (HQ)', value: 3.25, trend: 'up', status: 'healthy' },
          { id: 'ea', label: 'East Asia', value: 2.45, trend: 'up', status: 'healthy' },
          { id: 'sa', label: 'South Asia', value: 1.12, trend: 'flat', status: 'healthy' },
          { id: 'eu', label: 'Europe', value: 0.95, trend: 'up', status: 'healthy' },
          { id: 'am', label: 'Americas', value: 0.65, trend: 'flat', asleep: true, status: 'healthy' },
        ],
        otif: 98.7,
        otifStatus: 'healthy',
        activeShipments: 1284,
        inTransitValue: 214,
        avgLeadTimeDays: 4.2,
        supplierHealthPct: 97,
        promisesKept: 14203,
        promisesTotal: 14391,
        opsHeadline: 'ALL SYSTEMS NOMINAL',
      },
      p1: {
        revenueTotal: 8.51,
        revenueDeltaPct: 3.4,
        revenueTrend: 'up',
        revenueByRegion: [
          { id: 'sea', label: 'SE Asia (HQ)', value: 3.28, trend: 'flat', status: 'warning' },
          { id: 'ea', label: 'East Asia', value: 2.48, trend: 'up', status: 'healthy' },
          { id: 'sa', label: 'South Asia', value: 1.13, trend: 'flat', status: 'healthy' },
          { id: 'eu', label: 'Europe', value: 0.96, trend: 'up', status: 'healthy' },
          { id: 'am', label: 'Americas', value: 0.66, trend: 'flat', asleep: true, status: 'healthy' },
        ],
        otif: 96.1,
        otifStatus: 'warning',
        activeShipments: 1284,
        inTransitValue: 214,
        avgLeadTimeDays: 4.5,
        supplierHealthPct: 91,
        promisesKept: 14120,
        promisesTotal: 14391,
        opsHeadline: 'OTIF DEGRADING',
      },
      p2: {
        revenueTotal: 8.55,
        revenueDeltaPct: 0.1,
        revenueTrend: 'flat',
        revenueByRegion: [
          { id: 'sea', label: 'SE Asia (HQ)', value: 3.28, trend: 'down', status: 'critical' },
          { id: 'ea', label: 'East Asia', value: 2.50, trend: 'flat', status: 'healthy' },
          { id: 'sa', label: 'South Asia', value: 1.14, trend: 'flat', status: 'healthy' },
          { id: 'eu', label: 'Europe', value: 0.97, trend: 'flat', status: 'healthy' },
          { id: 'am', label: 'Americas', value: 0.66, trend: 'flat', asleep: true, status: 'healthy' },
        ],
        otif: 84.0,
        otifStatus: 'critical',
        activeShipments: 1284,
        inTransitValue: 214,
        avgLeadTimeDays: 6.8,
        supplierHealthPct: 42,
        promisesKept: 14015,
        promisesTotal: 14391,
        opsHeadline: 'SUPPLIER OFFLINE — SE ASIA',
      },
      p3: {
        revenueTotal: 8.55,
        revenueDeltaPct: 0.0,
        revenueTrend: 'flat',
        revenueByRegion: [
          { id: 'sea', label: 'SE Asia (HQ)', value: 3.28, trend: 'flat', status: 'critical' },
          { id: 'ea', label: 'East Asia', value: 2.50, trend: 'flat', status: 'healthy' },
          { id: 'sa', label: 'South Asia', value: 1.14, trend: 'flat', status: 'healthy' },
          { id: 'eu', label: 'Europe', value: 0.97, trend: 'flat', status: 'healthy' },
          { id: 'am', label: 'Americas', value: 0.66, trend: 'flat', asleep: true, status: 'healthy' },
        ],
        otif: 84.0,
        otifStatus: 'critical',
        activeShipments: 1284,
        inTransitValue: 214,
        avgLeadTimeDays: 6.5,
        supplierHealthPct: 45,
        promisesKept: 14015,
        promisesTotal: 14391,
        opsHeadline: 'SWARM RESPONDING',
      },
      p4: {
        revenueTotal: 8.55,
        revenueDeltaPct: 0.0,
        revenueTrend: 'flat',
        revenueByRegion: [
          { id: 'sea', label: 'SE Asia (HQ)', value: 3.28, trend: 'flat', status: 'warning' },
          { id: 'ea', label: 'East Asia', value: 2.50, trend: 'flat', status: 'healthy' },
          { id: 'sa', label: 'South Asia', value: 1.14, trend: 'flat', status: 'healthy' },
          { id: 'eu', label: 'Europe', value: 0.97, trend: 'flat', status: 'healthy' },
          { id: 'am', label: 'Americas', value: 0.66, trend: 'flat', asleep: true, status: 'healthy' },
        ],
        otif: 86.0,
        otifStatus: 'warning',
        activeShipments: 1284,
        inTransitValue: 214,
        avgLeadTimeDays: 5.1,
        supplierHealthPct: 78,
        promisesKept: 14210,
        promisesTotal: 14391,
        opsHeadline: 'AWAITING AUTHORIZATION',
      },
      p5: {
        revenueTotal: 8.61,
        revenueDeltaPct: 3.5,
        revenueTrend: 'up',
        revenueByRegion: [
          { id: 'sea', label: 'SE Asia (HQ)', value: 3.32, trend: 'up', status: 'healthy' },
          { id: 'ea', label: 'East Asia', value: 2.51, trend: 'up', status: 'healthy' },
          { id: 'sa', label: 'South Asia', value: 1.15, trend: 'up', status: 'healthy' },
          { id: 'eu', label: 'Europe', value: 0.97, trend: 'up', status: 'healthy' },
          { id: 'am', label: 'Americas', value: 0.66, trend: 'flat', asleep: true, status: 'healthy' },
        ],
        otif: 97.2,
        otifStatus: 'healthy',
        activeShipments: 1284,
        inTransitValue: 214,
        avgLeadTimeDays: 4.3,
        supplierHealthPct: 96,
        promisesKept: 14360,
        promisesTotal: 14391,
        opsHeadline: 'REROUTE ACTIVE — RECOVERED',
      },
    },
  },
  intro: {
    title: 'GLOBAL OPERATIONS TWIN — LIVE',
    subtitle: 'Cymbal Logistics · a living digital twin of every shipment, port & route on Earth',
    kpis: [
      { label: 'Assets Tracked', value: '12,480' },
      { label: 'Regions Online', value: '5 / 5' },
      { label: 'Agents On Watch', value: '5 · 24/7' },
      { label: 'Promises In Flight', value: '14,391' },
    ],
    // Global coverage points where the swarm is continuously watching. Spread
    // across regions/timezones incl. the Americas (asleep at 08:14 ICT).
    coveragePoints: [
      { id: 'cov-bangkok', lat: 13.7563, lng: 100.5018 },
      { id: 'cov-singapore', lat: 1.3521, lng: 103.8198 },
      { id: 'cov-shanghai', lat: 31.2304, lng: 121.4737 },
      { id: 'cov-hongkong', lat: 22.3193, lng: 114.1694 },
      { id: 'cov-tokyo', lat: 35.6895, lng: 139.6917 },
      { id: 'cov-mumbai', lat: 19.076, lng: 72.8777 },
      { id: 'cov-dubai', lat: 25.2048, lng: 55.2708 },
      { id: 'cov-rotterdam', lat: 51.9244, lng: 4.4777 },
      { id: 'cov-london', lat: 51.5072, lng: -0.1276 },
      { id: 'cov-newyork', lat: 40.7128, lng: -74.006 },
      { id: 'cov-losangeles', lat: 34.0522, lng: -118.2437 },
      { id: 'cov-santos', lat: -23.9608, lng: -46.3336 },
    ],
  },
};
